### ISSUE TITLE
This application is currently not functional

### ISSUE THREAD

**Issue by Mtax-Development** [Mtax-Development/GMS2_RPC#1]
As the functionality of this application is dependent on the application list, it has not been functional ever since GameMaker Studio 2 was rebranded to GameMaker. A simple fix could have been issued and released as Version 3, but instead the application is aimed to be rewritten from ground-up and planned for cross-platform compatibility and to possibly feature new functionality. It will also be rebranded in the process, so please stay tuned and be prepared for this repository to be listed under a new name in the future.

**Comment by Mtax-Development** [comment]
An update on the above announcement:

This application is in active development ever since the announcement was made, but no commits were made even after almost a month has passed, because most of the time was spent time on confirming which features were possible to do and how to implement them. It turned out that the process of porting the application cross-platform requires a fair amount of low-level tinkering and this is the reason for why it takes such a long time. I would like to thank you for your patience.

**Comment by Mtax-Development** [comment]
Further update on the above announcement:

After an extensive research period followed by a short hiatus, I would like to announce that Version 3 has now entered active development. After the initial rework is done, the code will be committed to the `preview` branch for a public review. After the preview period, the repository will be renamed, the code will be committed to the `master` branch and a new release will be available.

**Comment by Mtax-Development** [comment]
Another update on the above announcement:

The development is again under a hiatus due to a bug in a library that the rework is based on and lack of time to dedicate on development. The project is not cancelled, however and will be continued when possible.

Thank you for your understanding.

**Comment by kenan238** [comment]
waiting for this to be finished

**Comment by Mtax-Development** [comment]
Thank you for your support. The current plan is to resume the development early after New Year's Eve.

**Comment by Captainpax** [comment]
Still waiting <3

**Comment by Mtax-Development** [comment]
Whew, that was one long journey. Proud to announce that the overhaul of **GMS2_RPC** titled **GameMaker Companion** is now in public testing phase, available on the [`preview`](https://github.com/Mtax-Development/GMS2_RPC/tree/preview) branch and as a [release](https://github.com/Mtax-Development/GMS2_RPC/releases/tag/2.0.0-preview). Expected to be fully finished and released by early/mid March. When it does, this repository will be renamed to **GameMaker Companion**.

Apologies for this taking such a long time. I initially intended for this rewrite to be an element of a C# portfolio. While developing it, I found a GML job instead. Now that I am open to hiring again, I went ahead and decided to finish it, but even work aside, there were many, many, many complications with making it compatible cross-platform, which took much more time, than it could be expected from an application of such otherwise simple design. But it is here now, useable on all concurrent Operating Systems that GameMaker can be used on. Although for Microsoft's systems, the minimum system requirement was raised from Windows 7 to Windows 10.

This preview has some minor unfinished things behind the scenes, but all major features so far planned for this release are there. As the rebranding suggests, I am open to ideas for what else could be included in an application of this form, to have it function as a properly featured companion application for GameMaker. Do note that none of included features can modify or reverse engineer GameMaker IDE itself or its related files. After I reached them about it, Yoyogames explicitly forbade me from including such features, basing on their Terms of Service. This severely limits what could be done, although modifying user's project files should be fine, as such tools have existed for a long time and are widely used. You can share your ideas and code reviews below or try reach me in any way you wish to.

***

@kenan238 @Captainpax @catshift

**Comment by Captainpax** [comment]
<3 will try it when home. THANKS SO MUCH!

**Comment by Mtax-Development** [comment]
Second preview has been released and can be downloaded in the [releases tab](https://github.com/Mtax-Development/GameMakerCompanion/releases). With it, the repository renaming process has been finished. This preview includes everything planned to be included in the next version and is considered finished, apart from any potential issues that might be found during few next weeks. For that reason, it is titled as "Release Candidate", so feedback is welcome. Once that time passes, the final release will be made in early April.

This release includes experimental builds for ARM processors, although I do not have machines to actually test them — if anyone reading this has access to a machine with an ARM processor able to run **GameMaker Companion**, I will be grateful for information on whether or not it actually works there.

As always, please report any issues you find that have not been documented previously. Thank you for your help and patience.

***

**UPDATE:** The release will be postponed from early April into May or June.

**Comment by Mtax-Development** [comment]
I will close now this issue as [GameMaker Companion Release 1](https://github.com/Mtax-Development/GameMakerCompanion/releases/tag/2.0.0) has been fully finished and this application is functional again. Feel free to open another issue if there are problems with it.
