### ISSUE TITLE
Does not recognize the GameMaker LTS version

### ISSUE THREAD

**Issue by CST1229** [Mtax-Development/GMS2_RPC#2]
Basically, the title. I have GameMaker Companion running, and if I open standard GameMaker it shows up in Discord and works properly. But with the LTS version, no Discord RPC.
I assume this is just because LTS has a different executable name (`GameMaker-LTS.exe`), which is not in [this array](https://github.com/Mtax-Development/GameMakerCompanion/blob/ef92498db27a556c72f3e0241f3167bbde6e9a57/Source/Component/Tracker.cs#L33-L39) in the code.

**Comment by Mtax-Development** [comment]
Thank you for bringing my attention to this. It should be fixed as of commit [`3eaac87`](https://github.com/Mtax-Development/GameMakerCompanion/commit/3eaac87487322031b3f808375d6da2db2a43a86e) and [GameMaker Companion Release 1](https://github.com/Mtax-Development/GameMakerCompanion/releases/tag/2.0.0). I will close this issue now, but please feel free to open a new one if you notice this or any other problem persisting.
